name: stripe_backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  shelf: ^1.4.0
  shelf_router: ^1.0.0
  stripe_sdk: ^5.0.0 # or use stripe official package for dart if available, or http package to call stripe API directly
  dotenv: ^4.0.0
  http: ^1.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
